// Code generated by gin-react-admin codegen. DO NOT EDIT.
// 本文件由代码生成器生成，重新生成会覆盖手工修改。
package system

import (
	commonResponse "server/model/common/response"
	generatedModel "server/model/system"
 querypkg "server/pkg/query"
 "gorm.io/gorm"
)

var aiArticleFilters = []querypkg.QueryFilter{
	{Param: "title", Column: "title", Op: "like"},
	{Param: "status", Column: "status", Op: "eq"},
}

var aiArticleSortable = map[string]string{"sort": "sort"}

func AiarticleList(db *gorm.DB, query map[string]string) (*commonResponse.PageResult, error) {
	var data []generatedModel.Aiarticle
	return querypkg.PageListFiltered(db, query, &generatedModel.Aiarticle{}, &data, aiArticleFilters, aiArticleSortable, "id DESC", true)
}

func CreateAiarticle(db *gorm.DB, data map[string]interface{}) (*generatedModel.Aiarticle, error) {
	return querypkg.CreateRecord[generatedModel.Aiarticle](db, "ai_article", data)
}

func UpdateAiarticle(db *gorm.DB, id string, data map[string]interface{}) (*generatedModel.Aiarticle, error) {
	return querypkg.UpdateRecord[generatedModel.Aiarticle](db, "ai_article", id, data)
}

func DeleteAiarticle(db *gorm.DB, id string) error {
	return querypkg.SoftDeleteRecord(db, "ai_article", id)
}
