package system

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	systemModel "server/model/system"
	systemResponse "server/model/system/response"

	"gorm.io/gorm"
)

func buildGoPreviewFiles(ctx codegenContext) []systemResponse.CodegenPreviewFile {
	model := renderGoModel(ctx)
	service := renderGoService(ctx)
	api := renderGoAPI(ctx)
	router := renderGoRouter(ctx)
	return []systemResponse.CodegenPreviewFile{
		{Path: filepath.Join(ctx.BackendModelPath, ctx.BusinessName+".go"), Content: model, Group: "backend"},
		{Path: filepath.Join(ctx.BackendServicePath, ctx.BusinessName+".go"), Content: service, Group: "backend"},
		{Path: filepath.Join(ctx.BackendAPIPath, ctx.BusinessName+".go"), Content: api, Group: "backend"},
		{Path: filepath.Join(ctx.BackendRoutePath, ctx.BusinessName+".go"), Content: router, Group: "backend"},
	}
}

func buildFrontendPreviewFiles(ctx codegenContext) []systemResponse.CodegenPreviewFile {
	return []systemResponse.CodegenPreviewFile{
		{Path: filepath.Join(ctx.FrontendPageDir, "index.tsx"), Content: renderFrontendIndex(ctx), Group: "frontend"},
		{Path: filepath.Join(ctx.FrontendPageDir, "edit.tsx"), Content: renderFrontendEdit(ctx), Group: "frontend"},
		{Path: ctx.FrontendAPIPath, Content: renderFrontendAPI(ctx), Group: "frontend"},
	}
}

func renderGoModel(ctx codegenContext) string {
	var fields []string
	usesTime := false
	for _, column := range ctx.Columns {
		fieldType := goType(column)
		if strings.Contains(fieldType, "time.Time") {
			usesTime = true
		}
		jsonTag := toCamelCase(column.ColumnName)
		// 软删除标记列不对外输出。
		if strings.EqualFold(column.ColumnName, "delete_time") {
			jsonTag = "-"
		}
		fields = append(fields, fmt.Sprintf("\t%s %s `json:\"%s\" gorm:\"column:%s\"`", toPascalCase(column.ColumnName), fieldType, jsonTag, column.ColumnName))
	}
	importBlock := ""
	if usesTime {
		importBlock = "\nimport \"time\"\n"
	}
	return fmt.Sprintf(`// Code generated by gin-react-admin codegen. DO NOT EDIT.
// 本文件由代码生成器生成，重新生成会覆盖手工修改。
package %s
%s
type %s struct {
%s
}

func (%s) TableName() string {
	return "%s"
}
`, ctx.PackageName, importBlock, ctx.ClassName, strings.Join(fields, "\n"), ctx.ClassName, ctx.Table.TableNameValue)
}

func renderGoService(ctx codegenContext) string {
	filters := make([]string, 0, len(ctx.QueryColumns))
	for _, column := range ctx.QueryColumns {
		op := defaultString(column.QueryType, "eq")
		filters = append(filters, fmt.Sprintf("\t{Param: \"%s\", Column: \"%s\", Op: \"%s\"},", toCamelCase(column.ColumnName), column.ColumnName, op))
	}
	sortable := make([]string, 0)
	for _, column := range ctx.Columns {
		if column.IsSort == 2 {
			sortable = append(sortable, fmt.Sprintf("\"%s\": \"%s\"", toCamelCase(column.ColumnName), column.ColumnName))
		}
	}

	softDelete := codegenUsesSoftDelete(ctx)
	deleteBody := fmt.Sprintf("querypkg.DeleteRecord(db, &generatedModel.%s{}, id)", ctx.ClassName)
	if softDelete {
		deleteBody = fmt.Sprintf("querypkg.SoftDeleteRecord(db, \"%s\", id)", ctx.Table.TableNameValue)
	}

	content := fmt.Sprintf(`// Code generated by gin-react-admin codegen. DO NOT EDIT.
// 本文件由代码生成器生成，重新生成会覆盖手工修改。
package %s

import (
	commonResponse "server/model/common/response"
	generatedModel "server/model/%s"
 querypkg "server/pkg/query"
 "gorm.io/gorm"
)

var %sFilters = []querypkg.QueryFilter{
%s
}

var %sSortable = map[string]string{%s}

func %sList(db *gorm.DB, query map[string]string) (*commonResponse.PageResult, error) {
	var data []generatedModel.%s
	return querypkg.PageListFiltered(db, query, &generatedModel.%s{}, &data, %sFilters, %sSortable, "id DESC", %t)
}

func Create%s(db *gorm.DB, data map[string]interface{}) (*generatedModel.%s, error) {
	return querypkg.CreateRecord[generatedModel.%s](db, "%s", data)
}

func Update%s(db *gorm.DB, id string, data map[string]interface{}) (*generatedModel.%s, error) {
	return querypkg.UpdateRecord[generatedModel.%s](db, "%s", id, data)
}

func Delete%s(db *gorm.DB, id string) error {
	return %s
}
`, ctx.PackageName, ctx.PackageName, ctx.BusinessApiName, strings.Join(filters, "\n"), ctx.BusinessApiName, strings.Join(sortable, ", "), ctx.ClassName, ctx.ClassName, ctx.ClassName, ctx.BusinessApiName, ctx.BusinessApiName, softDelete, ctx.ClassName, ctx.ClassName, ctx.ClassName, ctx.Table.TableNameValue, ctx.ClassName, ctx.ClassName, ctx.ClassName, ctx.Table.TableNameValue, ctx.ClassName, deleteBody)
	return content
}

// codegenUsesSoftDelete 只有在选择软删除模型且表里确实有 delete_time 列时才启用软删，
// 避免生成的查询对无该列的表报 Unknown column。
func codegenUsesSoftDelete(ctx codegenContext) bool {
	if ctx.Table.GenerateModel != 1 {
		return false
	}
	for _, column := range ctx.Columns {
		if strings.EqualFold(column.ColumnName, "delete_time") {
			return true
		}
	}
	return false
}

func renderGoAPI(ctx codegenContext) string {
	systemAPIImport := "\tsystemAPI \"server/api/system\"\n"
	systemAPIQualifier := "systemAPI."
	if ctx.PackageName == "system" {
		systemAPIImport = ""
		systemAPIQualifier = ""
	}
	content := fmt.Sprintf(`// Code generated by gin-react-admin codegen. DO NOT EDIT.
// 本文件由代码生成器生成，重新生成会覆盖手工修改。
package %s

import (
%s	generatedService "server/service/%s"

	gormInit "server/setup/gorm"
 "github.com/gin-gonic/gin"
)

func %sList(c *gin.Context) {
 db, err := gormInit.Gorm.Get("ai_system")
 if err != nil { systemAPI.SuccessOrFail(c, nil, err); return }
	result, err := generatedService.%sList(db.WithContext(c.Request.Context()), systemAPI.QueryMap(c))
	systemAPI.SuccessOrFail(c, result, err)
}

func Create%s(c *gin.Context) {
 db, err := gormInit.Gorm.Get("ai_system")
 if err != nil { systemAPI.SuccessOrFail(c, nil, err); return }
	data, ok := systemAPI.BindJSONMap(c)
	if !ok {
		return
	}
	result, err := generatedService.Create%s(db.WithContext(c.Request.Context()), data)
	systemAPI.SuccessOrFail(c, result, err)
}

func Update%s(c *gin.Context) {
 db, err := gormInit.Gorm.Get("ai_system")
 if err != nil { systemAPI.SuccessOrFail(c, nil, err); return }
	data, ok := systemAPI.BindJSONMap(c)
	if !ok {
		return
	}
	result, err := generatedService.Update%s(db.WithContext(c.Request.Context()), c.Param("id"), data)
	systemAPI.SuccessOrFail(c, result, err)
}

func Delete%s(c *gin.Context) {
 db, err := gormInit.Gorm.Get("ai_system")
 if err != nil { systemAPI.SuccessOrFail(c, nil, err); return }
	systemAPI.SuccessOrFail(c, map[string]interface{}{}, generatedService.Delete%s(db.WithContext(c.Request.Context()), c.Param("id")))
}
`, ctx.PackageName, systemAPIImport, ctx.PackageName, ctx.ClassName, ctx.ClassName, ctx.ClassName, ctx.ClassName, ctx.ClassName, ctx.ClassName, ctx.ClassName, ctx.ClassName)
	content = strings.ReplaceAll(content, `gormInit.Gorm.Get("ai_system")`, "gormInit.Gorm.Get("+strconv.Quote(sourceOrDefault(stringValue(ctx.Table.Source)))+")")
	return strings.ReplaceAll(content, "systemAPI.", systemAPIQualifier)
}

func renderGoRouter(ctx codegenContext) string {
	// 权限码与 syncCodegenMenus 自动插入的按钮菜单一一对应（{routePath}/index 等）。
	return fmt.Sprintf(`// Code generated by gin-react-admin codegen. DO NOT EDIT.
// 本文件由代码生成器生成，重新生成会覆盖手工修改。
package %s

import (
	generatedAPI "server/api/%s"
	"server/middleware"

	"github.com/gin-gonic/gin"
)

func Register%sRoutes(group *gin.RouterGroup) {
	group.GET("/%s/index", middleware.Perm("%s/index"), generatedAPI.%sList)
	group.POST("/%s", middleware.Perm("%s/create"), generatedAPI.Create%s)
	group.PUT("/%s/:id", middleware.Perm("%s/update"), generatedAPI.Update%s)
	group.DELETE("/%s/:id", middleware.Perm("%s/destroy"), generatedAPI.Delete%s)
}
`, ctx.PackageName, ctx.PackageName, ctx.ClassName,
		ctx.RoutePath, ctx.RoutePath, ctx.ClassName,
		ctx.RoutePath, ctx.RoutePath, ctx.ClassName,
		ctx.RoutePath, ctx.RoutePath, ctx.ClassName,
		ctx.RoutePath, ctx.RoutePath, ctx.ClassName)
}

// frontendSearchControlFor 根据页面组件和查询操作符生成搜索控件。
func frontendSearchControlFor(column systemModel.ToolGenerateColumn) frontendControl {
	label := columnLabel(column)
	base := strings.ToLower(stringValue(column.ColumnType))
	multiple := column.QueryType == "in" || column.QueryType == "notin"
	if column.QueryType == "between" {
		switch column.ViewType {
		case "date":
			format := "YYYY-MM-DD"
			picker, showTime := "", ""
			if strings.HasPrefix(base, "year") {
				format, picker = "YYYY", ` picker="year"`
			}
			if regexp.MustCompile(`^(datetime|timestamp)`).MatchString(base) {
				format, showTime = "YYYY-MM-DD HH:mm:ss", " showTime"
			}
			return frontendControl{jsx: `<DatePicker.RangePicker` + picker + showTime + ` style={{ width: "100%" }} />`, antd: []string{"DatePicker"}, isArray: true, dateFormat: format}
		case "time":
			return frontendControl{jsx: `<TimePicker.RangePicker style={{ width: "100%" }} />`, antd: []string{"TimePicker"}, isArray: true, dateFormat: "HH:mm:ss"}
		default:
			return frontendControl{jsx: `<QueryRange` + map[bool]string{true: ` numeric`}[isNumericBaseType(base)] + ` />`, customs: []customImport{{"QueryRange", "@/components/query-range"}}, isArray: true}
		}
	}
	if column.ViewType == "select" || column.ViewType == "treeSelect" || column.ViewType == "cascader" {
		return frontendOptionControlFor(column, multiple)
	}
	if column.ViewType == "saSelect" || column.ViewType == "radio" || column.ViewType == "checkbox" {
		mode := ""
		if multiple {
			mode = ` mode="multiple"`
		}
		return frontendControl{jsx: `<Ith5Select dict="` + stringValue(column.DictType) + `"` + frontendValueTypeProp(column) + mode + ` placeholder="请选择` + label + `" />`, customs: []customImport{{"Ith5Select", "@/components/ith5ui/ith5-select"}}, isArray: multiple}
	}
	switch column.ViewType {
	case "date":
		format, picker, showTime := "YYYY-MM-DD", "", ""
		if strings.HasPrefix(base, "year") {
			format, picker = "YYYY", ` picker="year"`
		}
		if regexp.MustCompile(`^(datetime|timestamp)`).MatchString(base) {
			format, showTime = "YYYY-MM-DD HH:mm:ss", " showTime"
		}
		return frontendControl{jsx: `<DatePicker` + picker + showTime + ` style={{ width: "100%" }} />`, antd: []string{"DatePicker"}, dateFormat: format}
	case "time":
		return frontendControl{jsx: `<TimePicker style={{ width: "100%" }} />`, antd: []string{"TimePicker"}, dateFormat: "HH:mm:ss"}
	case "userSelect":
		return frontendControl{jsx: `<AuthSelect />`, customs: []customImport{{"AuthSelect", "@/components/auth-select"}}}
	case "cityLinkage":
		return frontendControl{jsx: `<CityLinkage />`, customs: []customImport{{"CityLinkage", "@/components/city-linkage"}}, isArray: true}
	case "inputTag":
		return frontendControl{jsx: `<Select mode="tags" open={false} tokenSeparators={[","]} />`, antd: []string{"Select"}, isArray: true}
	}
	if multiple {
		return frontendControl{jsx: `<Select mode="tags" open={false} tokenSeparators={[","]} placeholder="输入后回车添加` + label + `" />`, antd: []string{"Select"}, isArray: true}
	}
	if column.ViewType == "inputNumber" || isNumericBaseType(base) {
		return frontendControl{jsx: `<InputNumber style={{ width: "100%" }} placeholder="请输入` + label + `" />`, antd: []string{"InputNumber"}}
	}
	return frontendControl{jsx: `<Input placeholder="请输入` + label + `" allowClear />`, antd: []string{"Input"}}
}

func renderFrontendIndex(ctx codegenContext) string {
	antdSet := map[string]struct{}{"Col": {}, "Form": {}, "message": {}}
	customSet := map[string]string{}
	searchFields := make([]string, 0)
	dateFields := make([]string, 0)
	arrayFields := make([]string, 0)
	for _, column := range ctx.QueryColumns {
		control := frontendSearchControlFor(column)
		for _, item := range control.antd {
			antdSet[item] = struct{}{}
		}
		for _, item := range control.customs {
			customSet[item.name] = item.path
		}
		name := toCamelCase(column.ColumnName)
		if control.dateFormat != "" {
			dateFields = append(dateFields, fmt.Sprintf(`  { name: "%s", format: "%s" },`, name, control.dateFormat))
		}
		if control.isArray {
			arrayFields = append(arrayFields, fmt.Sprintf("%q", name))
		}
		searchFields = append(searchFields, fmt.Sprintf(`            <Col span={6}>
              <Form.Item name="%s" label="%s">
                %s
              </Form.Item>
            </Col>`, name, columnLabel(column), control.jsx))
	}

	listColumns := make([]string, 0)
	for _, column := range ctx.ListColumns {
		name := toCamelCase(column.ColumnName)
		dictProps := ""
		if dict := stringValue(column.DictType); dict != "" {
			dictProps = fmt.Sprintf(`, type: "dict", dict: "%s"`, dict)
		}
		listColumns = append(listColumns, fmt.Sprintf(`          { title: "%s", dataIndex: "%s", key: "%s"%s }`, columnLabel(column), name, name, dictProps))
	}

	customImports := ""
	for _, name := range sortedKeys(customSet) {
		customImports += fmt.Sprintf("\nimport %s from \"%s\";", name, customSet[name])
	}
	transformBlock := buildFrontendSearchTransforms(dateFields, arrayFields)
	dayjsImport := ""
	apiExpression := ctx.BusinessApiName + "ListApi"
	if len(dateFields) > 0 {
		dayjsImport = "\nimport type { Dayjs } from \"dayjs\";"
	}
	if transformBlock != "" {
		apiExpression = fmt.Sprintf("(params: Record<string, unknown>) => %sListApi(toSearchParams(params))", ctx.BusinessApiName)
	}

	return fmt.Sprintf(`// 本文件由代码生成器生成，重新生成会覆盖手工修改。
import { useRef } from "react";
import { %s } from "antd";%s
import Ith5Table, { type TableRef } from "@/components/ith5ui/ith5-table";%s
import { %sDeleteApi, %sListApi } from "@/api/%s/%s";
import %sEdit, { type %sEditRef } from "./edit";
%s
const %sIndex = () => {
  const tableRef = useRef<TableRef>(null);
  const editRef = useRef<%sEditRef>(null);

  return (
    <>
      <Ith5Table
        ref={tableRef}
        searchFields={
          <>
%s
          </>
        }
        options={{
          api: %s,
          add: { show: true, auth: ["%s/create"], func: () => editRef.current?.open("add") },
          edit: { show: true, auth: ["%s/update"], func: (record: { id: number }) => editRef.current?.open("edit", record) },
          delete: {
            show: true,
            auth: ["%s/destroy"],
            func: async (record: { id: number }) => {
              await %sDeleteApi(record.id);
              message.success("删除成功");
              tableRef.current?.refresh();
            },
          },
        }}
        columns={[
%s
        ]}
      />
      <%sEdit ref={editRef} onSuccess={() => tableRef.current?.refresh()} />
    </>
  );
};

export default %sIndex;
`, joinSortedKeys(antdSet), dayjsImport, customImports, ctx.BusinessApiName, ctx.BusinessApiName, ctx.PackageName, ctx.BusinessName, ctx.ClassName, ctx.ClassName, transformBlock, ctx.ClassName, ctx.ClassName, strings.Join(searchFields, "\n"), apiExpression, ctx.RoutePath, ctx.RoutePath, ctx.RoutePath, ctx.BusinessApiName, strings.Join(listColumns, ",\n"), ctx.ClassName, ctx.ClassName)
}

func buildFrontendSearchTransforms(dateFields, arrayFields []string) string {
	if len(dateFields) == 0 && len(arrayFields) == 0 {
		return ""
	}
	var out strings.Builder
	if len(dateFields) > 0 {
		out.WriteString("\nconst SEARCH_DATE_FIELDS: Array<{ name: string; format: string }> = [\n")
		out.WriteString(strings.Join(dateFields, "\n"))
		out.WriteString("\n];\n")
	}
	if len(arrayFields) > 0 {
		out.WriteString("\nconst SEARCH_ARRAY_FIELDS = [" + strings.Join(arrayFields, ", ") + "];\n")
	}
	out.WriteString("\nconst toSearchParams = (values: Record<string, unknown>) => {\n  const next = { ...values };\n")
	if len(dateFields) > 0 {
		out.WriteString("  SEARCH_DATE_FIELDS.forEach(({ name, format }) => {\n    const value = next[name];\n    next[name] = Array.isArray(value)\n      ? value.map((item) => (item as Dayjs).format(format))\n      : value ? (value as Dayjs).format(format) : undefined;\n  });\n")
	}
	if len(arrayFields) > 0 {
		out.WriteString("  SEARCH_ARRAY_FIELDS.forEach((name) => {\n    if (Array.isArray(next[name])) next[name] = next[name].filter((item) => item !== undefined && item !== \"\").join(\",\");\n  });\n")
	}
	out.WriteString("  return next;\n};\n")
	return out.String()
}

// frontendControl 描述一个表单字段生成出的控件及其附带需求（导入、值转换等）。
type frontendControl struct {
	jsx        string
	itemExtra  string
	comment    string
	verb       string
	isArray    bool
	dateFormat string
	antd       []string
	customs    []customImport
}

type customImport struct {
	name string
	path string
}

func frontendValueTypeProp(column systemModel.ToolGenerateColumn) string {
	if isNumericBaseType(stringValue(column.ColumnType)) {
		return ` valueType="number"`
	}
	return ""
}

func frontendOptionNodes(nodes []codegenOptionNode, valueType string) []codegenOptionNode {
	result := make([]codegenOptionNode, 0, len(nodes))
	for _, node := range nodes {
		if valueType == "number" {
			switch value := node.Value.(type) {
			case string:
				if parsed, err := strconv.ParseFloat(value, 64); err == nil {
					node.Value = parsed
				}
			}
		} else {
			node.Value = fmt.Sprint(node.Value)
		}
		node.Children = frontendOptionNodes(node.Children, valueType)
		result = append(result, node)
	}
	return result
}

func frontendOptionControlFor(column systemModel.ToolGenerateColumn, multiple bool) frontendControl {
	config, _ := parseCodegenOptionConfig(column)
	valueType := "string"
	if isNumericBaseType(stringValue(column.ColumnType)) {
		valueType = "number"
	}
	multipleProp := ""
	if multiple {
		multipleProp = ` mode="multiple"`
	}
	if stringValue(column.OptionSource) == optionSourceStatic {
		options, _ := json.Marshal(frontendOptionNodes(config.Options, valueType))
		switch column.ViewType {
		case "treeSelect":
			checkable := ""
			if multiple {
				checkable = " treeCheckable"
			}
			return frontendControl{jsx: `<TreeSelect allowClear` + checkable + ` treeData={` + string(options) + `} />`, antd: []string{"TreeSelect"}, verb: "请选择", isArray: multiple}
		case "cascader":
			multipleAttribute := ""
			if multiple {
				multipleAttribute = " multiple"
			}
			return frontendControl{jsx: `<Cascader allowClear` + multipleAttribute + ` options={` + string(options) + `} />`, antd: []string{"Cascader"}, verb: "请选择", isArray: true}
		default:
			return frontendControl{jsx: `<Select allowClear` + multipleProp + ` options={` + string(options) + `} />`, antd: []string{"Select"}, verb: "请选择", isArray: multiple}
		}
	}
	params := []byte("{}")
	if config.Params != nil {
		params, _ = json.Marshal(config.Params)
	}
	props := fmt.Sprintf(` url=%q dataPath=%q labelField=%q valueField=%q childrenField=%q params={%s} valueType=%q`, config.Path, config.DataPath, defaultString(config.LabelField, "label"), defaultString(config.ValueField, "value"), defaultString(config.ChildrenField, "children"), string(params), valueType)
	switch column.ViewType {
	case "treeSelect":
		checkable := ""
		if multiple {
			checkable = " treeCheckable"
		}
		return frontendControl{jsx: `<RemoteTreeSelect` + props + checkable + ` />`, customs: []customImport{{"RemoteTreeSelect", "@/components/remote-tree-select"}}, verb: "请选择", isArray: multiple}
	case "cascader":
		multipleAttribute := ""
		if multiple {
			multipleAttribute = " multiple"
		}
		return frontendControl{jsx: `<RemoteCascader` + props + multipleAttribute + ` />`, customs: []customImport{{"RemoteCascader", "@/components/remote-cascader"}}, verb: "请选择", isArray: true}
	default:
		return frontendControl{jsx: `<RemoteSelect` + props + multipleProp + ` />`, customs: []customImport{{"RemoteSelect", "@/components/remote-select"}}, verb: "请选择", isArray: multiple}
	}
}

// frontendControlFor 把 view_type 映射为生成的 antd/业务控件。
func frontendControlFor(column systemModel.ToolGenerateColumn) frontendControl {
	label := columnLabel(column)
	dict := stringValue(column.DictType)
	base := strings.ToLower(stringValue(column.ColumnType))

	switch column.ViewType {
	case "password":
		return frontendControl{jsx: `<Input.Password placeholder="请输入` + label + `" />`, antd: []string{"Input"}, verb: "请输入"}
	case "textarea":
		return frontendControl{jsx: `<Input.TextArea rows={4} placeholder="请输入` + label + `" />`, antd: []string{"Input"}, verb: "请输入"}
	case "inputNumber":
		return frontendControl{jsx: `<InputNumber style={{ width: "100%" }} placeholder="请输入` + label + `" />`, antd: []string{"InputNumber"}, verb: "请输入"}
	case "inputTag":
		return frontendControl{jsx: `<Select mode="tags" open={false} tokenSeparators={[","]} placeholder="输入后回车添加` + label + `" />`, antd: []string{"Select"}, verb: "请输入", isArray: true}
	case "switch":
		return frontendControl{jsx: `<Switch />`, itemExtra: ` getValueProps={(value) => ({ checked: value === 1 })} normalize={(value) => (value ? 1 : 2)}`, antd: []string{"Switch"}, verb: "请选择"}
	case "slider":
		return frontendControl{jsx: `<Slider />`, antd: []string{"Slider"}, verb: "请选择"}
	case "select", "treeSelect", "cascader":
		return frontendOptionControlFor(column, false)
	case "saSelect":
		return frontendControl{jsx: `<Ith5Select dict="` + dict + `"` + frontendValueTypeProp(column) + ` placeholder="请选择` + label + `" />`, customs: []customImport{{"Ith5Select", "@/components/ith5ui/ith5-select"}}, verb: "请选择"}
	case "radio":
		return frontendControl{jsx: `<Ith5Radio dict="` + dict + `"` + frontendValueTypeProp(column) + ` />`, customs: []customImport{{"Ith5Radio", "@/components/ith5ui/ith5-radio"}}, verb: "请选择"}
	case "checkbox":
		return frontendControl{jsx: `<Ith5Checkbox dict="` + dict + `"` + frontendValueTypeProp(column) + ` />`, customs: []customImport{{"Ith5Checkbox", "@/components/ith5ui/ith5-checkbox"}}, verb: "请选择", isArray: true}
	case "date":
		if strings.HasPrefix(base, "year") {
			return frontendControl{jsx: `<DatePicker picker="year" style={{ width: "100%" }} placeholder="请选择` + label + `" />`, antd: []string{"DatePicker"}, verb: "请选择", dateFormat: "YYYY"}
		}
		if regexp.MustCompile(`^(datetime|timestamp)`).MatchString(base) {
			return frontendControl{jsx: `<DatePicker showTime style={{ width: "100%" }} placeholder="请选择` + label + `" />`, antd: []string{"DatePicker"}, verb: "请选择", dateFormat: "YYYY-MM-DD HH:mm:ss"}
		}
		return frontendControl{jsx: `<DatePicker style={{ width: "100%" }} placeholder="请选择` + label + `" />`, antd: []string{"DatePicker"}, verb: "请选择", dateFormat: "YYYY-MM-DD"}
	case "time":
		return frontendControl{jsx: `<TimePicker style={{ width: "100%" }} placeholder="请选择` + label + `" />`, antd: []string{"TimePicker"}, verb: "请选择", dateFormat: "HH:mm:ss"}
	case "userSelect":
		return frontendControl{jsx: `<AuthSelect />`, customs: []customImport{{"AuthSelect", "@/components/auth-select"}}, verb: "请选择"}
	case "cityLinkage":
		return frontendControl{jsx: `<CityLinkage />`, customs: []customImport{{"CityLinkage", "@/components/city-linkage"}}, verb: "请选择", isArray: true}
	case "uploadImage":
		return frontendControl{jsx: `<ImageUpload />`, customs: []customImport{{"ImageUpload", "@/components/image-upload"}}, verb: "请上传"}
	case "uploadFile":
		return frontendControl{jsx: `<FileUpload />`, customs: []customImport{{"FileUpload", "@/components/file-upload"}}, verb: "请上传"}
	case "wangEditor":
		return frontendControl{jsx: `<WangEditor />`, customs: []customImport{{"WangEditor", "@/components/wang-editor"}}, verb: "请输入"}
	default:
		if isNumericBaseType(base) {
			return frontendControl{jsx: `<InputNumber style={{ width: "100%" }} placeholder="请输入` + label + `" />`, antd: []string{"InputNumber"}, verb: "请输入"}
		}
		return frontendControl{jsx: `<Input placeholder="请输入` + label + `" />`, antd: []string{"Input"}, verb: "请输入"}
	}
}
func renderFrontendEdit(ctx codegenContext) string {
	initialFields := make([]string, 0)
	formItems := make([]string, 0)
	dateFields := make([]string, 0)
	arrayFields := make([]string, 0)
	antdSet := map[string]struct{}{"Form": {}, "Input": {}, "message": {}}
	customSet := map[string]string{}

	for _, column := range ctx.FormColumns {
		if isSystemColumnName(column.ColumnName) {
			continue
		}
		name := toCamelCase(column.ColumnName)
		label := columnLabel(column)
		control := frontendControlFor(column)

		for _, item := range control.antd {
			antdSet[item] = struct{}{}
		}
		for _, item := range control.customs {
			customSet[item.name] = item.path
		}
		if control.dateFormat != "" {
			dateFields = append(dateFields, fmt.Sprintf(`  { name: "%s", format: "%s" },`, name, control.dateFormat))
		}
		if control.isArray {
			arrayFields = append(arrayFields, fmt.Sprintf(`  { name: "%s", numeric: %t },`, name, isNumericBaseType(stringValue(column.ColumnType))))
		}
		initialFields = append(initialFields, fmt.Sprintf("  %s: %s,", name, frontendInitialValue(column, control)))

		rules := ""
		if column.IsRequired == 2 {
			rules = fmt.Sprintf(` rules={[{ required: true, message: "%s%s" }]}`, control.verb, label)
		}
		item := ""
		if control.comment != "" {
			item += fmt.Sprintf("        {/* %s */}\n", control.comment)
		}
		item += fmt.Sprintf(`        <Form.Item name="%s" label="%s"%s%s>
          %s
        </Form.Item>`, name, label, rules, control.itemExtra, control.jsx)
		formItems = append(formItems, item)
	}

	shell := frontendEditShell(ctx, antdSet, strings.Join(formItems, "\n"))
	needsTransform := len(dateFields) > 0 || len(arrayFields) > 0

	imports := fmt.Sprintf("import { %s } from \"antd\";", joinSortedKeys(antdSet))
	if len(dateFields) > 0 {
		imports += "\nimport dayjs from \"dayjs\";\nimport type { Dayjs } from \"dayjs\";"
	}
	for _, name := range sortedKeys(customSet) {
		imports += fmt.Sprintf("\nimport %s from \"%s\";", name, customSet[name])
	}

	transformBlock := ""
	openValues := "data"
	submitPrelude := ""
	submitPayload := "values"
	if needsTransform {
		transformBlock = buildFrontendTransforms(dateFields, arrayFields)
		openValues = "toFormValues(data)"
		submitPrelude = "\n      const payload = toSubmitValues(values);"
		submitPayload = "payload"
	}

	return fmt.Sprintf(`// 本文件由代码生成器生成，重新生成会覆盖手工修改。
import { forwardRef, useImperativeHandle, useState } from "react";
%s
import { %sCreateApi, %sUpdateApi } from "@/api/%s/%s";

export interface %sEditRef {
  open: (type?: "add" | "edit", data?: Record<string, unknown>) => void;
}

interface %sEditProps {
  onSuccess?: () => void;
}

const initialFormData = {
%s
};
%s
const %sEdit = forwardRef<%sEditRef, %sEditProps>(({ onSuccess }, ref) => {
  const [visible, setVisible] = useState(false);
  const [mode, setMode] = useState<"add" | "edit">("add");
  const [loading, setLoading] = useState(false);
  const [form] = Form.useForm();
  const title = "%s" + (mode === "edit" ? " - 编辑" : " - 新增");

  const open = (type: "add" | "edit" = "add", data?: Record<string, unknown>) => {
    setMode(type);
    form.resetFields();
    form.setFieldsValue(type === "edit" && data ? %s : initialFormData);
    setVisible(true);
  };

  const close = () => setVisible(false);

  const handleSubmit = async () => {
    try {
      setLoading(true);
      const values = await form.validateFields();%s
      if (mode === "add") {
        await %sCreateApi(%s);
      } else {
        await %sUpdateApi(values.id as number, %s);
      }
      message.success("操作成功");
      onSuccess?.();
      close();
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return;
    } finally {
      setLoading(false);
    }
  };

  useImperativeHandle(ref, () => ({ open }));

  return (
%s
  );
});

%sEdit.displayName = "%sEdit";

export default %sEdit;
`, imports, ctx.BusinessApiName, ctx.BusinessApiName, ctx.PackageName, ctx.BusinessName, ctx.ClassName, ctx.ClassName, strings.Join(initialFields, "\n"), transformBlock, ctx.ClassName, ctx.ClassName, ctx.ClassName, defaultString(stringValue(ctx.Table.MenuName), ctx.ClassName), openValues, submitPrelude, ctx.BusinessApiName, submitPayload, ctx.BusinessApiName, submitPayload, shell, ctx.ClassName, ctx.ClassName, ctx.ClassName)
}

// frontendEditShell 根据表单样式配置生成 Modal 或 Drawer 外壳。
func frontendEditShell(ctx codegenContext, antdSet map[string]struct{}, formItems string) string {
	width := fmt.Sprintf("{%d}", defaultInt(ctx.Table.FormWidth, 720))
	formBody := `      <Form form={form} labelCol={{ span: 4 }} wrapperCol={{ span: 18 }}>
        <Form.Item name="id" hidden>
          <Input />
        </Form.Item>
` + formItems + `
      </Form>`

	if ctx.Table.ComponentType == 2 {
		antdSet["Drawer"] = struct{}{}
		antdSet["Button"] = struct{}{}
		antdSet["Space"] = struct{}{}
		return `    <Drawer
      open={visible}
      title={title}
      width=` + width + `
      onClose={close}
      footer={
        <Space style={{ display: "flex", justifyContent: "flex-end" }}>
          <Button onClick={close}>取消</Button>
          <Button type="primary" loading={loading} onClick={handleSubmit}>
            确定
          </Button>
        </Space>
      }
    >
` + formBody + `
    </Drawer>`
	}

	antdSet["Modal"] = struct{}{}
	return `    <Modal open={visible} title={title} width=` + width + ` confirmLoading={loading} onOk={handleSubmit} onCancel={close}>
` + formBody + `
    </Modal>`
}

// buildFrontendTransforms 生成日期/数组字段在回显和提交时的转换代码。
func buildFrontendTransforms(dateFields, arrayFields []string) string {
	var out strings.Builder
	out.WriteString("\n")
	if len(dateFields) > 0 {
		out.WriteString("const DATE_FIELDS: Array<{ name: string; format: string }> = [\n")
		out.WriteString(strings.Join(dateFields, "\n"))
		out.WriteString("\n];\n\n")
	}
	if len(arrayFields) > 0 {
		out.WriteString("const ARRAY_FIELDS: Array<{ name: string; numeric: boolean }> = [\n")
		out.WriteString(strings.Join(arrayFields, "\n"))
		out.WriteString("\n];\n\n")
	}

	out.WriteString("const toFormValues = (data: Record<string, unknown>) => {\n")
	out.WriteString("  const next: Record<string, unknown> = { ...data };\n")
	if len(dateFields) > 0 {
		out.WriteString("  DATE_FIELDS.forEach(({ name }) => {\n    next[name] = next[name] ? dayjs(String(next[name])) : undefined;\n  });\n")
	}
	if len(arrayFields) > 0 {
		out.WriteString("  ARRAY_FIELDS.forEach(({ name, numeric }) => {\n    if (typeof next[name] === \"string\") {\n      const items = next[name] === \"\" ? [] : String(next[name]).split(\",\");\n      next[name] = numeric ? items.map(Number) : items;\n    }\n  });\n")
	}
	out.WriteString("  return next;\n};\n\n")

	out.WriteString("const toSubmitValues = (values: Record<string, unknown>) => {\n")
	out.WriteString("  const next: Record<string, unknown> = { ...values };\n")
	if len(dateFields) > 0 {
		out.WriteString("  DATE_FIELDS.forEach(({ name, format }) => {\n    next[name] = next[name] ? (next[name] as Dayjs).format(format) : undefined;\n  });\n")
	}
	if len(arrayFields) > 0 {
		out.WriteString("  ARRAY_FIELDS.forEach(({ name }) => {\n    if (Array.isArray(next[name])) {\n      next[name] = (next[name] as Array<string | number>).join(\",\");\n    }\n  });\n")
	}
	out.WriteString("  return next;\n};\n")
	return out.String()
}

func joinSortedKeys(set map[string]struct{}) string {
	keys := make([]string, 0, len(set))
	for key := range set {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return strings.Join(keys, ", ")
}

func sortedKeys(set map[string]string) []string {
	keys := make([]string, 0, len(set))
	for key := range set {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func renderFrontendAPI(ctx codegenContext) string {
	return fmt.Sprintf(`// 本文件由代码生成器生成，重新生成会覆盖手工修改。
import request from "@/utils/request";

export const %sListApi = (params?: Record<string, unknown>) => request.get("/%s/index", { params });
export const %sCreateApi = (data: Record<string, unknown>) => request.post("/%s", data);
export const %sUpdateApi = (id: string | number, data: Record<string, unknown>) => request.put("/%s/" + id, data);
export const %sDeleteApi = (id: string | number) => request.delete("/%s/" + id);
`, ctx.BusinessApiName, ctx.RoutePath, ctx.BusinessApiName, ctx.RoutePath, ctx.BusinessApiName, ctx.RoutePath, ctx.BusinessApiName, ctx.RoutePath)
}

// goType 推断 Go 字段类型；可空列一律用指针，避免 GORM 扫描 NULL 报错。
func goType(column systemModel.ToolGenerateColumn) string {
	base := strings.ToLower(stringValue(column.ColumnType))
	nullable := column.IsRequired != 2
	switch {
	case regexp.MustCompile(`^(date|datetime|timestamp|time|year)`).MatchString(base):
		return "*time.Time"
	case regexp.MustCompile(`^(decimal|float|double)`).MatchString(base):
		if nullable {
			return "*float64"
		}
		return "float64"
	case regexp.MustCompile(`^(tinyint|smallint|mediumint|int|bigint)`).MatchString(base):
		if nullable {
			return "*int"
		}
		return "int"
	default:
		if nullable {
			return "*string"
		}
		return "string"
	}
}

func frontendInitialValue(column systemModel.ToolGenerateColumn, control frontendControl) string {
	if control.isArray {
		return "[]"
	}
	if control.dateFormat != "" {
		return "undefined"
	}
	// 开关按项目约定 1 是 / 2 否，默认关闭。
	if column.ViewType == "switch" {
		return "2"
	}
	if isNumericBaseType(stringValue(column.ColumnType)) {
		return "undefined"
	}
	return `""`
}

func columnLabel(column systemModel.ToolGenerateColumn) string {
	return defaultString(stringValue(column.ColumnComment), column.ColumnName)
}

func resolveFrontendRoot(value string) string {
	value = defaultString(value, "web")
	if filepath.IsAbs(value) {
		return value
	}
	candidates := []string{
		filepath.Clean(value),
		filepath.Join("..", value),
		filepath.Join("..", "..", value),
	}
	for _, candidate := range candidates {
		if info, err := os.Stat(candidate); err == nil && info.IsDir() {
			return candidate
		}
	}
	return value
}

func toPascalCase(value string) string {
	parts := regexp.MustCompile(`[_\-\s]+`).Split(value, -1)
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		out.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			out.WriteString(strings.ToLower(part[1:]))
		}
	}
	return out.String()
}

func toCamelCase(value string) string {
	pascal := toPascalCase(value)
	if pascal == "" {
		return ""
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}

func toKebabCase(value string) string {
	value = regexp.MustCompile(`([a-z0-9])([A-Z])`).ReplaceAllString(value, "$1-$2")
	value = strings.ReplaceAll(value, "_", "-")
	value = strings.ReplaceAll(value, " ", "-")
	value = regexp.MustCompile(`-+`).ReplaceAllString(value, "-")
	return strings.Trim(strings.ToLower(value), "-")
}

func syncCodegenMenus(ctx codegenContext) ([]uint, error) {
	parentID := uint(0)
	if ctx.Table.BelongMenuID != nil {
		parentID = *ctx.Table.BelongMenuID
	}
	page, err := upsertCodegenMenu(parentID, defaultString(stringValue(ctx.Table.MenuName), ctx.ClassName), ctx.RoutePath, "/"+ctx.RoutePath, ctx.PackageName+"/"+ctx.BusinessName+"/index", "M", 10)
	if err != nil {
		return nil, err
	}
	ids := []uint{page.ID}
	actions := []struct {
		name string
		code string
		sort uint16
	}{
		{"列表", ctx.RoutePath + "/index", 10},
		{"新增", ctx.RoutePath + "/create", 20},
		{"编辑", ctx.RoutePath + "/update", 30},
		{"删除", ctx.RoutePath + "/destroy", 40},
	}
	for _, action := range actions {
		item, err := upsertCodegenMenu(page.ID, action.name, action.code, "", "", "B", action.sort)
		if err != nil {
			return ids, err
		}
		ids = append(ids, item.ID)
	}
	return ids, nil
}

func upsertCodegenMenu(parentID uint, name, code, route, component, typ string, sortValue uint16) (systemModel.AISystemMenu, error) {
	db, err := systemDB()
	if err != nil {
		return systemModel.AISystemMenu{}, err
	}
	var existing systemModel.AISystemMenu
	err = db.Where("code = ? AND delete_time IS NULL", code).First(&existing).Error
	payload := map[string]interface{}{
		"parent_id":   parentID,
		"name":        name,
		"code":        code,
		"route":       route,
		"component":   component,
		"type":        typ,
		"icon":        "AppstoreOutlined",
		"sort":        sortValue,
		"is_hidden":   2,
		"is_layout":   1,
		"status":      1,
		"update_time": gorm.Expr("NOW()"),
	}
	if typ == "B" {
		payload["is_hidden"] = 1
		payload["icon"] = ""
	}
	if errorsIsRecordNotFound(err) {
		menu := systemModel.AISystemMenu{}
		payload["create_time"] = gorm.Expr("NOW()")
		if err := db.Table("ai_system_menu").Create(payload).Error; err != nil {
			return menu, err
		}
		err = db.Where("code = ? AND delete_time IS NULL", code).First(&menu).Error
		return menu, err
	}
	if err != nil {
		return existing, err
	}
	err = db.Model(&systemModel.AISystemMenu{}).Where("id = ?", existing.ID).Updates(payload).Error
	if err != nil {
		return existing, err
	}
	err = db.Where("id = ?", existing.ID).First(&existing).Error
	return existing, err
}

func errorsIsRecordNotFound(err error) bool {
	return errors.Is(err, gorm.ErrRecordNotFound)
}
