// Code generated by gin-react-admin codegen. DO NOT EDIT.
// 本文件由代码生成器生成，重新生成会覆盖手工修改。
package system

import (
	generatedAPI "server/api/system"
	"server/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterAiarticleRoutes(group *gin.RouterGroup) {
	group.GET("/system/ai-article/index", middleware.Perm("system/ai-article/index"), generatedAPI.AiarticleList)
	group.POST("/system/ai-article", middleware.Perm("system/ai-article/create"), generatedAPI.CreateAiarticle)
	group.PUT("/system/ai-article/:id", middleware.Perm("system/ai-article/update"), generatedAPI.UpdateAiarticle)
	group.DELETE("/system/ai-article/:id", middleware.Perm("system/ai-article/destroy"), generatedAPI.DeleteAiarticle)
}
