// Code generated by gin-react-admin codegen. DO NOT EDIT.
// 本文件由代码生成器生成，重新生成会覆盖手工修改。
package system

import (
	generatedService "server/service/system"

	gormInit "server/setup/gorm"
 "github.com/gin-gonic/gin"
)

func AiarticleList(c *gin.Context) {
 db, err := gormInit.Gorm.Get("ai_system")
 if err != nil { SuccessOrFail(c, nil, err); return }
	result, err := generatedService.AiarticleList(db.WithContext(c.Request.Context()), QueryMap(c))
	SuccessOrFail(c, result, err)
}

func CreateAiarticle(c *gin.Context) {
 db, err := gormInit.Gorm.Get("ai_system")
 if err != nil { SuccessOrFail(c, nil, err); return }
	data, ok := BindJSONMap(c)
	if !ok {
		return
	}
	result, err := generatedService.CreateAiarticle(db.WithContext(c.Request.Context()), data)
	SuccessOrFail(c, result, err)
}

func UpdateAiarticle(c *gin.Context) {
 db, err := gormInit.Gorm.Get("ai_system")
 if err != nil { SuccessOrFail(c, nil, err); return }
	data, ok := BindJSONMap(c)
	if !ok {
		return
	}
	result, err := generatedService.UpdateAiarticle(db.WithContext(c.Request.Context()), c.Param("id"), data)
	SuccessOrFail(c, result, err)
}

func DeleteAiarticle(c *gin.Context) {
 db, err := gormInit.Gorm.Get("ai_system")
 if err != nil { SuccessOrFail(c, nil, err); return }
	SuccessOrFail(c, map[string]interface{}{}, generatedService.DeleteAiarticle(db.WithContext(c.Request.Context()), c.Param("id")))
}
